# This is a config for E2B sandbox template.
# You can use template ID (lwm0csai453c9egr2l9s) or template name (anthropic-claude-code) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("anthropic-claude-code") # Sync sandbox
# sandbox = await AsyncSandbox.create("anthropic-claude-code") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('anthropic-claude-code')

team_id = "460355b3-4f64-48f9-9a16-4442817f79f5"
memory_mb = 4_096
cpu_count = 4
dockerfile = "e2b.Dockerfile"
template_name = "anthropic-claude-code"
template_id = "lwm0csai453c9egr2l9s"
